### ISSUE TITLE
Editor bug

### ISSUE THREAD

**Issue by ralfjoneskof** [GameHackFan/ffaee#1] opened 2022-07-21 14:18 UTC
There is an error making any modification to the anniversary rom. When saved, the game only comes with 2 or 3 Bred (Enemies). It would be great if the tool wasn't a web version and could edit the original rom as well. Being able to color the clothes of the characters of your choice.

**Comment by GameHackFan** [comment] 2022-07-29 00:27
Hi,

About the original version, there are a lot of downside which makes the AE version a better choice for this editor, some of them are the color feature already coded, in the original I would have to write a pallete replace and a sprite remapper and that is an annoying and time consuming task, I would have to code a feature to allow players to select the same character and also treat color conflict, most of these things come for free on AE. Another thing is, the original version doesn't have enough empty space, so I would have to expand the ROM, which means people wouldn't be able to replace the original version with the hack made by this editor and just play, they would need to also build an emulator to support it, which for me is a huge downside, currently you can generate a ROM with this tool and replace the main AE version with the hack and you don't even need to build an emulator, you can use HBMame or Fightcade 2 to play the generated hack without any headache. Another downside is I would have to port all the tool to the original version, since the byte position of things there are in different places. So, it is just a lot of work and basically 0 gain, I feel like it is a waste of time actually, the AE version has more features, enough empty space to edit it without having to expand the ROM and also being able to use the generated hacks in some emulators that are already available, even play online without any headache are just way too much of an advantage in favor of AE. The only downside of the AE version is that it introduced a bug that happens sometimes when you hit your partner that is in a complete different line, very far away, but it can be fixed, or even better would be to disable friendly fire. At the end, for me, it is not worth to consider the original version, if someone wants to do it, I have no objections, that person can fork the project and port it to the original, but I won't do it myself as I already pointed out the reasons, I feel like the AE is the better version for this editor in general.

About the bug, you need to be more specific, if you point out what you have done to reach it, then I can try to do the same steps and see what is happening, without that information, I can't reproduce it, so I am not able to do anything about it. It would be nice if you can tell me step by step of what you did.


Thank you for your time and your feedback.

**Comment by GameHackFan** [comment] 2022-08-02 13:44
I made a test today and the level editor seems to be working properly.

One thing that you need to notice is, final fight is not like the other beat'em ups, if you place the enemy way too far from the camera, the game will spawn and despawn the enemy instantly, so check if that is not what was happening to you.

Remember to use the save and load preset to keep the progress of your editing, also let me know if this issue is still happening to you or not.

Have a nice editing, =).

**Comment by ralfjoneskof** [comment] 2022-08-03 03:17
@GameHackFan Thanks a lot for the support. As soon as I have some time I'll test it out soon!

**Comment by GameHackFan** [comment] 2022-08-03 13:04
If you can replicate it, a good idea is to save a preset with the enemies positioned in a way that causes the issue, the preset will have all the configurations you made and everyone that uses the same preset will have the same result, then you post it here or upload it somewhere and I will be able to see what is going on.

**Comment by GameHackFan** [comment] 2022-09-21 20:07
I am closing the issue because I didn't get an answer about it, but you if have the same problem again, feel free to open an issue, =).

**Closed as completed by GameHackFan** 2022-09-21 20:07 UTC
